### PR TITLE
Feature-card

### PR DESCRIPTION
**Pull request by liepsneletech**
Styled component as described. Please notice these moments:

1. I added layout structure (container, row etc) in order you could check the card in natural width which has to be flexible and will depend on the layout (col-3 / col-4). After your check, I'll remove it.

2. The  orange color in base.css wasn't correct, so I changed it.

3. For media query I used min-width because trying to use mobile-first approach. Let me know if you have better solution.

### CODE REVIEW

**Review by Rasosm — APPROVED** [review]
Thank you for changing orange:)

**Review by EvgenySivaykin — DISMISSED** [review]
OK

**Review by zilva149 — APPROVED** [review]

**Review by EvgenySivaykin — APPROVED** [review]
OK

**Review by Dorenus — APPROVED** [review]
Good job

**Review by Rasosm — APPROVED** [review]

**Pull request merged**
