### PR TITLE
readme file

### PR DESCRIPTION
**Pull request by EvgenySivaykin**
Added README.md file

### CODE REVIEW

**Review by zilva149 — COMMENTED** [review]
Good job.

**Review by liepsneletech — CHANGES_REQUESTED** [review]
I really like the structure, just suggest change the authors' icon, because this one is related to Christmas.

**Review by Dorenus — APPROVED** [review]
Great README  file!

**Review by zilva149 — APPROVED** [review]
Approve

**Review by Dorenus — APPROVED** [review]

**Review by liepsneletech — APPROVED** [review]

**Pull request merged**
