### PR TITLE
Added html-templates.md with comments

### PR DESCRIPTION
**Pull request by liepsneletech**
Extra file including all components' html structure in one place for reusing purposes.

### CODE REVIEW

**Review by zilva149 — APPROVED** [review]
Looks good

**Review by zilva149 — CHANGES_REQUESTED** [review]
After recheking I found one issue - comments are hidden, so we will not see separation in a displayed result. I think we should separate each component with a heading, like this:
`
// HEADING
<comment>
actual code
<end comment> 
`
Just a suggestion.

**Comment by liepsneletech** [comment]
> After recheking I found one issue - comments are hidden, so we will not see separation in a displayed result. I think we should separate each component with a heading, like this: `// HEADING` `<comment>` `actual code` `<end comment>` Just a suggestion.

How about using ### to make markdown headings? and backtics for start and end comments?

**Comment by liepsneletech** [comment]
> > After recheking I found one issue - comments are hidden, so we will not see separation in a displayed result. I think we should separate each component with a heading, like this: `// HEADING` `<comment>` `actual code` `<end comment>` Just a suggestion.
> 
> How about using ### to make markdown headings? and backtics for start and end comments?

Or put everything into html file?

**Comment by zilva149** [comment]
> Or put everything into html file?
 html file will probably be easier to handle.

**Review by Dorenus — APPROVED** [review]
From what I see everything is good now, since comments are not hidden anymore, and we will have the needed separation for future code. Good job!

**Pull request merged**
